version: '3.8'

services:
  # Eureka Server
  eureka:
    build: ./eureka
    image: rayene8/backend-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  # API Gateway
  gateway:
    build: ./gateway
    image: rayene8/backend-gateway:latest
    container_name: gateway-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: school_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservices-network

  # School Microservice
  school:
    build: ./microservices/student
    image: aminehor/school
    container_name: school-service
    depends_on:
      - mysql
      - eureka
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/school_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
